import type { Metadata } from "next";
import { Anek_Bangla } from "next/font/google";
import "./globals.css";

const anekBangla = Anek_Bangla({
  variable: "--font-anek-bangla",
  display: "swap",
  weight: ["400", "500", "600", "700"],
  style: ["normal"],
  subsets: ["latin"],
  fallback: ["system-ui", "sans-serif"],
  preload: true
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${anekBangla.className} antialiased`}>{children}</body>
    </html>
  );
}
